# Site settings
title: Transit Techies NYC
email: 
description: > # this means to ignore newlines until "baseurl:"
  Transit Techies NYC: Bringing together people who love transit, transporation, and smart cities!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://transittechies.nyc" # the base hostname & protocol for your site
github_username:  transittechies

# Build settings
markdown: kramdown
highlighter: rouge
